# This Action mostly follows these docs
# https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
---
name: Publish Python 🐍 distribution 📦 to GitHub

description: "Publishes Python packages to GitHub."

inputs:
  #github-token:
  #  description: "A GitHub PAT used to commit and push generated SVGs back into the repository."
  #  required: true
  package-name:
    # TODO pulled from artifacts
    description: "The name of the Python package to publish."
    required: true
runs:
  using:
    "composite"
    #needs:
    #  - publish-to-pypi
    #runs-on: ubuntu-latest

    #permissions:
    #  contents: write
    #  id-token: write

  steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Sign the dists with Sigstore
      uses: sigstore/gh-action-sigstore-python@v1.11
      with:
        inputs: >-
          ./dist/*.tar.gz
          ./dist/*.whl
    - name: Create GitHub Release
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      # TODO change the release notes to use the changelog
      run: >-
        gh release create
        '${{ github.ref_name }}'
        --repo '${{ github.repository }}'
        --notes ""
    - name: Upload artifact signatures to GitHub Release
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: >-
        gh release upload
        '${{ github.ref_name }}' dist/**
        --repo '${{ github.repository }}'
